name: check_N

on:
  # schedule:
  #   - cron: '20,50 * * * *'
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Clone private repo
      env:
        PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
      run: |
        git clone https://x-access-token:${PAT_GITHUB}@github.com/iamCristYE/TunnelBear.git
        cd TunnelBear

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: OpenVPN
      run: |
        date
        bash -c "$IP_COMMAND"
        echo
        echo "$TEST"
        date
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved ffmpeg
        pip install requests yt-dlp
        sudo echo -e "${TB_USER}\n${TB_PASS}" > TunnelBear.auth
        sudo openvpn --config TunnelBear_New_Zealand.ovpn --auth-user-pass TunnelBear.auth --daemon
        sleep 60
        date
        bash -c "$IP_COMMAND"
        echo
        date
      env:
        IP_COMMAND: ${{ secrets.IP_COMMAND }}
        TB_USER: ${{ secrets.TB_USER }}
        TB_PASS: ${{ secrets.TB_PASS }}
        TEST: ${{ vars.TEST }}

    
    - name: Run Python script
      run: |
        cd TunnelBear
        date
        python check.py
        date
      env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CHANNEL_URL: ${{ secrets.CHANNEL_URL }}
          COOKIE: ${{ secrets.COOKIE }}
          ARTIST_CHANNEL_URL: https://music.youtube.com/channel/UCov14bMqiBPdPLFuHQ_K-eg

    - name: Stop OpenVPN
      run: |
        date
        bash -c "$IP_COMMAND"
        echo
        sudo killall openvpn || date
        date
      env:
        IP_COMMAND: ${{ secrets.IP_COMMAND }}